# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dhUcW_O80Sr-FuQIFtw1Fsr0XD7mQ1YZ
"""



import pandas as pd
df = pd.DataFrame ({'ism':['Muhammadaziz','Nurmuhammad','Merojiddin','Shuxrat', 'Shohrux','Oybek','Shoyat','Mohichexra','Xurshid','Ibrohim'],
                    'Familya':['Rozaliyev','Jumanazarov','Bahtiyorjonov','Shamsiddinov','Salimov','Akramov','Maqsudov','Yusupaliyeva','Odilov','Burxonov'],
                    'Yoshi':['19','19','19','19','19','19','19','20','19','19'],
                    'Kursi':['2','2','2','2','2','2','2','2','2','2']
                    })
print (df)

df.to_excel('Sessiya.xlsx',index=False, sheet_name='sheet1')